name: Test Backend Server Health

on:
  pull_request:
    branches: ["main"]
    # paths: ["laravel-backend/**"]

jobs:
  Backend-Server-Health-Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./laravel-backend

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          composer update

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute Server Health Test
        run: php artisan test tests/Unit/ServerHealthTest.php
